spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth-server:9000

server:
  ssl:
    key-store-type: PKCS12
    key-store: ${KEY_STORE_PATH}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-alias: ${KEY_ALIAS}
    enabled: true